# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128)),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('is_main_page', models.BooleanField(default=False)),
            ],
        ),
    ]
